### ISSUE TITLE
[Feature Request] AD User Account Creation Name Mapping

### ISSUE THREAD

**Issue by bstep1** [twocanoes/xcreds#172]
OIDC Allows specifying:
-First Name OIDC Mapping
-Last Name OIDC Mapping
-Full Name OIDC Mapping
-Username OIDC Mapping

Could use the same Mapping preferences for AD so that the account is created with the proper AD preferences to match the account whether it was created the first time logging in to the cloud (Using the preferences listed above) or connecting to the on premise AD at login.

Currently from AD the sAMAccountName looks like it is being used for the username and the Full name.

**Comment by bstep1** [comment]
I think you would need to create new preferences, as the OIDC Mapping  works correctly under the OIDC login window.

However if the user logs in to the computer using their AD credentials, the local account is created with the  username and fullname being set to the adusername which is the samaccountname.

I would like the accounts to be created the same whether first login was on AD or OIDC.

Sorry, in my attempts to get the bugs I identified yesterday documented, I now realize I didn't clearly state what that I am wanting parity mappings created for AD Mapping so the accounts are created with the same naming convention.  This information would be used when the account is initially created to properly create the local account. when logged in via AD:

-First Name AD Mapping
-Last Name AD Mapping
-Full Name AD Mapping
-Username AD Mapping

**Comment by jolegape** [comment]
I second this suggestion. The school I manage uses the CN field in AD for HR purposes. This means that when users log in to a mac using Xcreds, they see Firstname Lastname (employeeID). I'd love to be able to either map it to samaccountname so it only shows the username everywhere, or to displayName to show the full name.

![image](https://github.com/twocanoes/xcreds/assets/10903036/5eaf6f80-65c5-4dc7-b86d-30e6266171dc)
![image](https://github.com/twocanoes/xcreds/assets/10903036/f6f974a1-e65c-4170-92ec-9943e814fe10)

**Comment by twocanoes** [comment]
reused map_firstname, map_lastname, map_fullname, map_username from OIDC. Works the same if you put in AD attributes instead of claims.

**Comment by bstep1** [comment]
@twocanoes - 
I Couldn't seem to get the AD DisplayName to show up properly using map_fullname.
![Snag_dd28e1](https://github.com/twocanoes/xcreds/assets/87917989/d371ea98-498d-423c-9724-1a59f40e633a)
It looks like it may be mapping to the AD attribute userDisplayName (which doesn't exist) instead of displayName
![Snag_de90de](https://github.com/twocanoes/xcreds/assets/87917989/a01c2ab4-0841-4a7f-bac9-dc70be022e8b)

**Comment by twocanoes** [comment]
userDisplayName is set to displayName from LDAP:
           var userDisplayName = ldapResult["displayName"] ?? ""

@davelebbing can you test and see if it works for you?

**Comment by davelebbing** [comment]
Map user fields for AD do not appear to work as expected for me.  I set map_fullname to sn and when signing in, XCreds created the user account with the normal default behavior instead of the change expected for this setting.

**Comment by twocanoes** [comment]
I believe this was fixed with the other map_username issue. Please verify and close if working.

**Comment by davelebbing** [comment]
Need to demo.  Still not seeing this work as expected on 7130.

**Comment by twocanoes** [comment]
i think i found the issue. Please test in 7142 or later.

**Comment by davelebbing** [comment]
Build 7142 shows some success but also some issues.  Mapping the preference key `DisplayName` to the AD field `sn` did succeed to set full name to the AD user's last name.  But the manifest should be updated to list `DisplayName` instead of `map_fullname` for this or the app should be changed to support `map_fullname`.  

Also after creating the new user the menubar app shows un unexpected number value next to the icon.  

<img width="318" alt="Screenshot 2024-08-15 at 10 36 27 AM" src="https://github.com/user-attachments/assets/ae046452-d86c-4960-8092-14ae78fcddd8">

**Comment by davelebbing** [comment]
Tested build 7144 and this now looks good.

**Comment by davelebbing** [comment]
Reopening to review new feedback received.
