### ISSUE TITLE
Update login window when resolution changes

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#187]
Seeing an issue with window dimensions on macOS 14.4.  Upon boot, dimensions are wrong. If I kill loginwindow they are correct. Reboot and dimensions are wrong again. A guess is that Apple is changing resolution so may need to subscribe to NSScreen changes. This is on M1 Air. (edited)

**Comment by twocanoes** [comment]
I thnk this is fixed. can't replicate in current bulid.

**Comment by kcrawford** [comment]
This issue still exists in beta 5.0 (7087)

Note that it only presents on boot of Apple Silicon with FileVault not yet enabled.

**Comment by davelebbing** [comment]
@kcrawford I did a test on an M1 MacBook Air reset to factory settings and running XCreds 5.0 build 7087.  I could not replicate any issue with window dimensions upon system boot.  Would you have a screenshot or something showing the window dimensions issue you are seeing?

**Comment by kcrawford** [comment]
I have a support ticket open with twocanoes that has screenshots. Must reproduce at first boot without FileVault enabled and probably need a custom window size in XCreds profile.My testing was on M1 MacBook KyleSent from MobileOn Jul 15, 2024, at 4:49 PM, davelebbing ***@***.***> wrote:﻿
@kcrawford I did a test on an M1 MacBook Air reset to factory settings and running XCreds 5.0 build 7087.  I could not replicate any issue with window dimensions upon system boot.  Would you have a screenshot or something showing the window dimensions issue you are seeing?

**Comment by davelebbing** [comment]
@kcrawford, I was able to replicate this now.  @twocanoes, the attached screenshots show the login window dimensions changing when set at 800x800 and then clicking the switch login window button.  The login window initially renders all the way from the top of the screen to the bottom, then after switching login window and switching back it renders shorter and narrower with space noticeable above and below.
![LWScreenShot 2024-07-16 at 10 50 56 AM](https://github.com/user-attachments/assets/c2130eb7-bcbf-4ce3-9b7d-279c20fd4fbc)
![LWScreenShot 2024-07-16 at 10 50 57 AM](https://github.com/user-attachments/assets/abe1b8ac-e42d-406e-afcd-42704b1cbe5e)
![LWScreenShot 2024-07-16 at 10 51 29 AM](https://github.com/user-attachments/assets/8030e4ce-ac4f-4ea9-bdc9-62e73efbe406)
<img width="1440" alt="Screenshot 2024-07-16 at 10 52 51 AM" src="https://github.com/user-attachments/assets/bdce6407-a859-4c60-84d7-3ba36e348fe2">
<img width="762" alt="Screenshot 2024-07-16 at 10 52 55 AM" src="https://github.com/user-attachments/assets/230151fa-2a23-4935-a0d5-5d009d6f9f44">

**Comment by twocanoes** [comment]
OK, I think i got it now. Please verify it works then close or assign back to me.

**Comment by kcrawford** [comment]
Thanks! Can you create a release for me to test.

**Comment by twocanoes** [comment]
it is in the latest build.

tim

**Comment by kcrawford** [comment]
Does not seem to be fixed in my testing. Unless it was fixed in 7130 that just got released tonight.KyleOn Aug 6, 2024, at 10:51 AM, Twocanoes Software, Inc ***@***.***> wrote:﻿
it is in the latest build.
tim

**Comment by kcrawford** [comment]
And killing loginwindow fixes the size to match the config profile but now the window is off-center. 

Build 7118

**Comment by davisbr1** [comment]
I'm seeing a similar issue to this as well. I'm running macOS 14.6 on a M2 Mac mini, filevault not enabled, with a Dell external monitor attached. Screen after boot is the first screenshot, the second picture shows after clicking Switch Login Window twice, and the 3rd picture shows how it looks after clicking Switch Login Window for a second round.
<img width="1470" alt="XCreds1" src="https://github.com/user-attachments/assets/cb6934dd-e29c-4626-86b1-5e8a7fadacab">
<img width="1470" alt="XCreds2" src="https://github.com/user-attachments/assets/ae66da3d-11be-45a6-bbb1-7173e8f6d717">
<img width="1470" alt="XCreds3" src="https://github.com/user-attachments/assets/7c57ba8a-ab45-4355-a89e-83a69fffb4db">

**Comment by twocanoes** [comment]
@davisbr1 what build? I did a bunch of work on fixing that last night, so please try the last build.

**Comment by davisbr1** [comment]
5.0.7133

**Comment by twocanoes** [comment]
please test in build 7141 or later.

**Comment by davisbr1** [comment]
Issue is resolved for me on build 7146! Thanks!
